### ISSUE TITLE
Suggestions for single device type - with multiple different outputs.

### ISSUE THREAD

**Issue by lamiskin** [networktocode/ntc-ansible#12]
Hi Guys,

I just wanted to see if there has been any consideration for the same device types, but which return different output (and therefore the one template can't be used..??).

I'll explain where I've run in to this issue.

I am trying to get a structured response for "show mac address table".

On a 6500 chassis running 12.2(33)SXH5, on a WS-SUP720-3B the following is returned:
```
  vlan   mac address     type    learn     age              ports
------+----------------+--------+-----+----------+--------------------------
*  402  ac87.a30b.5bea   dynamic  Yes         15   Gi3/19
*  ---  0000.0c9f.f92e    static  No           -   Router
* 2640  0040.8ce8.04b7   dynamic  Yes          0   Po16
   310  9890.96d8.3716   dynamic  Yes         70   Te7/8
* 1441  0022.9091.54c2   dynamic  Yes          0   Po8
*  ---  0000.0c9f.f92e    static  No           -   Router
   270  f8b1.569d.8aa4   dynamic  Yes          0   Po17
* 2270  f01f.af14.a877   dynamic  Yes          0   Po306
* 2441  0022.9091.49b6   dynamic  Yes          5   Gi3/30
```

But on a WS-C3750G-24PS running 15.0(2)SE4 the following is returned:
```
 All    0180.c200.000f    STATIC      CPU
 All    0180.c200.0010    STATIC      CPU
 All    ffff.ffff.ffff    STATIC      CPU
   1    0024.50dd.9218    DYNAMIC     Gi1/0/24
   1    0025.8365.d019    DYNAMIC     Gi1/0/26
   1    0025.8367.4e99    DYNAMIC     Gi1/0/27
   1    2894.0faa.1806    DYNAMIC     Gi1/0/25
 270    0000.74cf.08c4    DYNAMIC     Gi1/0/25
 270    0000.859b.162d    DYNAMIC     Gi1/0/25
 270    000c.293a.a353    DYNAMIC     Gi1/0/25
 270    000c.293c.b42a    DYNAMIC     Gi1/0/25
 270    000c.2947.f994    DYNAMIC     Gi1/0/25
 270    000c.2957.1e6e    DYNAMIC     Gi1/0/25
 270    000c.295f.596b    DYNAMIC     Gi1/0/25
 270    000c.2969.161e    DYNAMIC     Gi1/0/25
 270    000c.296c.8a7c    DYNAMIC     Gi1/0/25
 270    000c.2978.f4b7    DYNAMIC     Gi1/0/25
```

Has anyone considered / have a plan on how to get all of the data from both outputs?

**Comment by jedelman8** [comment]
Ugh, this sucks.  Haven't thought too much about it, but we did have a plan to eliminate "vendor" (textfsm object) from being required as an Ansible param and only use "device_type" (netmiko object).  We were then going to extrapolate the "vendor" from the "device_type".

That being said, this should still be possible, if we reverse the logic.  Meaning we only keep "vendor" and not "device_type".  If we keep both, it's no issue at all, but it just hurts the user experience.

So...

We then take a "vendor" such as cisco_ios-c6k and are able to deduce what the netmiko "device_type" is - this format would assume that when a hyphen is in the "vendor", the left portion signifies the netmiko device type, and the right side signifies the platform.  This allows us to easily figure out the netmiko device type, but also ensures the command + vendor-platform uses the proper template.

Example:
```
Template, Hostname, Vendor_Type, Command
cisco_ios_show_mac_table-c6k.template, .*, cisco_ios-c6k, sh[[ow]] m[[ac]] ta[[ble]]
cisco_ios_show_mac_table-c3k.template, .*, cisco_ios-c3k, sh[[ow]] m[[ac]] ta[[ble]]
```

The only issue is then keeping a list of all of the vendors supported (because it's not vendors at this point, it's vendor-platform).  It is probably worth while to build a script to read the index file and auto-generate a markdown table, and store that in this project!  Can add that to the todo list.

What do you think?

**Comment by mzbenami** [comment]
The latest release on master uses @jedelman8 's idea and required only a 'platform' parameter, which should follow a naming convention that includes the netmiko device type. Appropriate changes to the index file for existing templates have been made.

**Comment by jedelman8** [comment]
Hi @lamiskin, I'm going to close this issue.  If you want to add these templates, that would be awesome.

They would both go in the `ntc_templates` directory, and both sets of test files would go into `cisco_ios/show_mac_table` directory, but be saved as `cisco_ios-c3k_show_mac_table.parsed (& raw)` and `cisco_ios-c6k_show_mac_table.parsed (& raw)` respectively.  And they would the appropriate platform within the template like this:

```
cisco_ios-c6k_show_mac_table.template, .*, cisco_ios-c6k, sh[[ow]] m[[ac]] ta[[ble]]
cisco_ios-c3k_show_mac_table.template, .*, cisco_ios-c3k, sh[[ow]] m[[ac]] ta[[ble]]
```
