### ISSUE TITLE
Password and secret data displayed in plain text

### ISSUE THREAD

**Issue by bobthebutcher** [networktocode/ntc-ansible#163]
When using the -vvv debugging level passwords and secrets are visible in plain text

**Comment by bobthebutcher** [comment]
"module_args": {
            "command": "show version",
            "connection": "ssh",
            "delay": "1",
            "file": null,
            "global_delay_factor": "1",
            "host": "lab-sw-01",
            "index_file": "index",
            "key_file": null,
            "local_file": null,
            "optional_args": {},
            "password": "H-iIm-Barrys-Password",
            "platform": "arista_eos",
            "port": null,
            "secret": null,
            "template_dir": "roles/ntc-ansible/ntc-templates/templates",
            "trigger_device_list": null,
            "use_keys": false,
            "use_templates": true,
            "username": "barry"
        }

**Comment by bobthebutcher** [comment]
submitted PR #161 to tackle this issue

**Comment by haind13** [comment]
Another issue:
with ntc-ansible, inventory host have var username and password
How can I hide this username & password in inventory file? 
(because If I build Ansible in my company with 1 server, and have many network administrators can use it, and they just use "cat" command to read file inventory is read username and password of me, all account in my company has use LDAP to sync all system)

**Comment by bobthebutcher** [comment]
If I understand you correctly I would use ansible vault to solve your problem. If its a shared system, then a service account rather than your own account could be a better option. Ansible tower handles this type of thing for you if you can justify the cost.

**Comment by itdependsnetworks** [comment]
Concur with @bobthebutcher

**Comment by GGabriele** [comment]
PR is merged. I'm closing this.
